# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='no description', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.CharField(default='no image', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='item_video_url',
            field=models.CharField(default='no url', max_length=200),
        ),
    ]
